services:
  nginx:
    image: nginx:stable
    container_name: gateway-nginx
    restart: always
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
      - ./nginx/logs:/var/log/nginx
    environment:
      - TZ=Asia/Seoul

  certbot:
    image: certbot/certbot
    container_name: gateway-certbot
    volumes:
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    depends_on:
      - nginx