apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-configmap
  labels:
    app: nginx
    env: {{ .Values.env }}
    release: {{ .Release.Name }}
data:
  nginx.conf: |
    http {
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      access_log  /var/log/nginx/access.log  main;
      sendfile        on;
      keepalive_timeout  65;

      #gzip  on;
      server {
        listen       80;
        server_name  _;

        location / {
          rewrite ^/(.*) /$1 break;
          proxy_pass http://{{ .Release.Name }}-web:4173;
        }
        

        location /api/ {
          rewrite ^/(api/.*)$ /$1 break;
          proxy_pass http://{{ .Release.Name }}-api:3000;
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
