apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    app: nginx
    env: {{ .Values.env }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
        env: {{ .Values.env }}
        release: {{ .Release.Name }}
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-nginx
          image: {{ .Values.nginx.image.name }}:{{ .Values.nginx.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              name: {{ .Release.Name }}-nginx-configmap
      volumes:
        - name: {{ .Release.Name }}-nginx-configmap
          configMap:
            name: {{ .Release.Name }}-nginx-configmap