apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  labels:
    app: web
    env: {{ .Values.env }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        env: {{ .Values.env }}
        release: {{ .Release.Name }}
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      restartPolicy: Always
      containers:
      - name: {{ .Release.Name }}-web
        image: {{ .Values.web.image.name }}:{{ .Values.web.image.tag }}
        imagePullPolicy: Always
        livenessProbe:
            exec:
              command:
                - curl
                - --silent
                - -f
                - http://{{ .Release.Name }}-web:4173/
            failureThreshold: 30
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
        ports:
          - containerPort: 4173